version: '3.7'
services:
  twitchbot:
    build:
      context: .
    image: xwillmarkthebot
    volumes:
      - /c/Users/sdste/Documents/Programming/xwillmarktheBot/logs/twitch:/etc/xwillmarktheBot/logs
      - /c/Users/sdste/Documents/Programming/xwillmarktheBot/Settings:/etc/xwillmarktheBot/Settings
    environment:
      - platform=twitch
    restart: unless-stopped
  discordbot:
    build:
      context: .
    image: xwillmarkthebot
    volumes:
      - /c/Users/sdste/Documents/Programming/xwillmarktheBot/logs/discord:/etc/xwillmarktheBot/logs
      - /c/Users/sdste/Documents/Programming/xwillmarktheBot/Settings:/etc/xwillmarktheBot/Settings
    environment:
      - platform=discord
    restart: unless-stopped
