version: '3.7'
services:
  twitchbot:
    build:
      context: .
    image: xwillmarkthebot
    volumes:
      - /xwillmarktheBot/volumes/logs/twitch:/etc/xwillmarktheBot/logs
      - /xwillmarktheBot/volumes/Settings:/etc/xwillmarktheBot/Settings
    environment:
      - platform=twitch
    restart: unless-stopped
  discordbot:
    build:
      context: .
    image: xwillmarkthebot
    volumes:
      - /xwillmarktheBot/volumes/logs/discord:/etc/xwillmarktheBot/logs
      - /xwillmarktheBot/volumes/Settings:/etc/xwillmarktheBot/Settings
    environment:
      - platform=discord
    restart: unless-stopped
